# Basic
title: 苏苏炎
subtitle: 静默
welcome_message: Test
description: 嗨，我是 苏苏炎 (@susuyan)
creator: <a href="http://susuyan.com">@susuyan</a>

url: "http://susuyan.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'https://susuyan.netlify.com/'}
    - {title: 关于, description: 了解更多关于我, url: 'https://susuyan.netlify.com/'}
    - {title: 订阅, description: 邮件订阅本站, url: '//store.objccn.io/subscribe'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"


# Comment
comment:
    disqus: susuyan
    # duoshuo:
# Social
social:
    weibo: susuyan12
    github: susuyan
    twitter: susuyan12
    # gplus: 107108267983477358170
    mail: susuyan@163.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: susuyan.com
